services:
  monitor:
    build: .
    image: kazever/kazever_monitor:v1.1
    container_name: system_monitor
    network_mode: host
    pid: "host"
    environment:
      - PROCFS_PATH=/host/proc
      - MONITOR_PASSWORD=YourOwnPassword
      - MONITOR_SECRET_KEY=A_LongString_to_MakeSure_the_Service_is_Safe
    volumes:
      - ./back/data:/app/back/data
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    restart: always
